-- Dados originais: relatório Meta Ads da ByteClass (Out/25 a Jul/26) e quadro da semana 27 a 31/07/2026
-- Descrições '.' do quadro original viraram NULL (não traziam informação)

INSERT INTO metrica_mensal (id, ano_mes, rotulo, gasto, cliques, conversas, cpc, cpa, fase) VALUES
    (1, '2025-10', 'Out/25', 985, 619, 87, 1.59, 11.32, 1),
    (2, '2025-11', 'Nov/25', 1328, 934, 106, 1.42, 12.53, 1),
    (3, '2025-12', 'Dez/25', 1100, 836, 114, 1.32, 9.65, 1),
    (4, '2026-01', 'Jan/26', 1411, 2203, 193, 0.64, 7.31, 2),
    (5, '2026-02', 'Fev/26', 1141, 1629, 139, 0.70, 8.21, 2),
    (6, '2026-03', 'Mar/26', 948, 1208, 113, 0.78, 8.38, 2),
    (7, '2026-04', 'Abr/26', 667, 1036, 73, 0.64, 9.13, 2),
    (8, '2026-05', 'Mai/26', 610, 521, 66, 1.17, 9.24, 3),
    (9, '2026-06', 'Jun/26', 612, 466, 64, 1.31, 9.57, 3),
    (10, '2026-07', 'Jul/26', 534, 484, 52, 1.10, 10.27, 3);

INSERT INTO tarefa (id, titulo, descricao, projeto, etapa, etapa_inicial, dia, ordem) VALUES
    ('a1a', 'A.1.a - Mapeamento', 'Reunião de finanças com fio solto — retomar e definir próxima ação.', 'MEDTREM', 'TODO', 'TODO', 'SEG', 1),
    ('a2a', 'A.2.a - ERP', 'Integração de dados e parametrização do sistema base.', 'MEDTREM', 'BACKLOG', 'BACKLOG', NULL, 2),
    ('a2b', 'A.2.b - Financeiro', 'Processos de recebimento.', 'MEDTREM', 'BACKLOG', 'BACKLOG', NULL, 3),
    ('a3', 'A.3 - Des. de Tecnologia', 'Frente técnica geral do MedTrem.', 'MEDTREM', 'BACKLOG', 'BACKLOG', NULL, 4),
    ('b1a', 'B.1.a - Gestão', 'Tarefa e prazo.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 5),
    ('b1b', 'B.1.b - Pedagógico', 'Conteúdo, instrutor, nível de aluno.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 6),
    ('b1c', 'B.1.c - Comercial', 'Converter lead em matrícula.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 7),
    ('b1d', 'B.1.d - Marketing', 'Criar conteúdo em redes digitais.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 8),
    ('b1e', 'B.1.e - CS', 'Tornar o aluno um cliente feliz.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 9),
    ('b1f', 'B.1.f - Financeiro', 'Pix e link de pagamento.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 10),
    ('b1g', 'B.1.g - Jurídico', 'Contrato e datas de matrícula ativada.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 11),
    ('b2a', 'B.2.a - Conteúdos', 'Ementa e escrever roteiros.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 12),
    ('b2b', 'B.2.b - Engajamento', 'Acompanhamento do aluno.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 13),
    ('b2c', 'B.2.c - Aula Presencial', 'Concentrar alunos em uma turma.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 14),
    ('b2d', 'B.2.d - Aula Gravada', 'Subir vídeos com prazo.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 15),
    ('b2e', 'B.2.e - Live', 'Aulas ao vivo online, Discord.', 'BYTECLASS', 'BACKLOG', 'BACKLOG', NULL, 16),
    ('b3a', 'B.3.a - Des. Plataforma', 'PRs, QA, backlogs — #133/#134/#135 fechados, #136 em revisão final.', 'BYTECLASS', 'DOING', 'DOING', 'SEG', 17),
    ('c1a', 'C.1.a - Estratégia', 'Business plan.', 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 18),
    ('c1b', 'C.1.b - Incubação', 'Projeto, documentação, pitch, edital.', 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 19),
    ('c2a', 'C.2.a - Desenvolvimento LP', 'Landing page.', 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 20),
    ('c2b', 'C.2.b - Desenvolvimento Plataforma', NULL, 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 21),
    ('c3a', 'C.3.a - Marketing', 'Conteúdo, audiência, cadastro, anúncio.', 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 22),
    ('c3b', 'C.3.b - Viagens Realizadas', 'Levantamento de tração.', 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 23),
    ('c3c', 'C.3.c - Prioridades', NULL, 'VOLTA_EXPRESS', 'BACKLOG', 'BACKLOG', NULL, 24),
    ('d1a', 'D.1.a - GitHub: Gestão de Projetos', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 25),
    ('d1b', 'D.1.b - learnTECH Plataforma', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 26),
    ('d1c', 'D.1.c - learnTECH Conteúdo', 'Roadmap: HD, YouTube, Notion, imagens.', 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 27),
    ('d2a', 'D.2.a - BQ Agenda Tech', 'Issue especificada, pronta para decisão final.', 'ECOSSISTEMA', 'TODO', 'TODO', 'TER', 28),
    ('d2b', 'D.2.b - Histórico Registrados', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 29),
    ('d2c', 'D.2.c - Famosos do Futuro', 'Curadoria de eventos futuros já iniciada.', 'ECOSSISTEMA', 'TODO', 'TODO', NULL, 30),
    ('d3a', 'D.3.a - Processo Seletivo', 'Inscrever, avançar em etapas, aprovar.', 'ECOSSISTEMA', 'QA', 'QA', NULL, 31),
    ('d4a', 'D.4.a - Pós Engenharia de Software', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 32),
    ('d4b', 'D.4.b - Certificação PMO', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 33),
    ('d4c', 'D.4.c - IA na Programação', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 34),
    ('d5a', 'D.5.a - Idioma para Conversação', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 35),
    ('d6a', 'D.6.a - Artigos dos Chats IA', 'Matéria-prima já existe, falta transformar em rascunho.', 'ECOSSISTEMA', 'TODO', 'TODO', 'SEX', 36),
    ('d7a', 'D.7.a - Projeto facilAdmin', NULL, 'ECOSSISTEMA', 'BACKLOG', 'BACKLOG', NULL, 37);
-- fim de V2__dados_originais.sql
